version: '2'
services:

  prometheus:
    depends_on:
      - prom-push-gw
      - prom-node-exporter
    image: alexswilliams/arm32v6-prometheus:2.8.1
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-volume:/etc/prometheus/data"
    environment:
      PROM_STORAGE_TSDB_RETENTION_TIME: "1y"
      PROM_STORAGE_TSDB_RETENTION_SIZE: "5GB"
    expose:
      - "9090"
    ports:
      - "9090:9090"

  prom-push-gw:
    image: alexswilliams/arm32v6-prometheus-push-gateway:0.7.0
    expose:
      - "9091"
    ports:
      - "9091:9091"

  #  prom-node-exporter:
  #    image: alexswilliams/arm32v6-prometheus-node-exporter:0.17.0
  #    user: root
  #    privileged: true
  #    volumes:
  #      - "/proc:/host/proc:ro"
  #      - "/:/host/root:ro"
  #      - "/sys:/host/sys:ro"
  #    environment:
  #      NODE_EXP_PATH_PROCFS: /host/proc
  #      NODE_EXP_PATH_ROOTFS: /host/root
  #      NODE_EXP_PATH_SYSFS: /host/sys
  #      NODE_EXP_COLLECTOR_FILESYSTEM_IGNORED_MOUNT_POINTS: ^/(sys|proc|dev|host|etc|var/lib/docker.+)($$|/)
  #      NODE_EXP_WEB_LISTEN_ADDRESS: ":9101"
  #    expose:
  #      - "9101"
  #    ports:
  #      - "9101:9101"

  tplink-scraper:
    depends_on:
      - prom-push-gw
    build:
      context: ./tplink-hs110-client
      dockerfile: Dockerfile.arm32v6
    environment:
      POLL_TIME_SECONDS: "5"
      TPLINK_HOST: "192.168.1.30"
      PUSH_GW_URL: "http://prom-push-gw:9091/metrics/job/tplink-scraper-1"

volumes:
  prometheus-volume:

