version: '3.7'
services:

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:6.0.2
    volumes:
      - type: volume
        source: grafana-volume
        target: /var/lib/grafana
        consistency: consistent
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    expose:
      - "3000"
    ports:
      - "3000:3000"

  prometheus:
    depends_on:
      - prom-push-gw
    image: prom/prometheus:v2.8.1
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-volume:/etc/prometheus/data"
    command: [ "--web.console.templates=/etc/prometheus/consoles", "--web.console.libraries=/etc/prometheus/console-libraries", "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.retention.time=1y", "--storage.tsdb.retention.size=5GB", "--web.enable-admin-api" ]
    expose:
      - "9090"
    ports:
      - "9090:9090"

  prom-push-gw:
    image: prom/pushgateway:v0.7.0
    expose:
      - "9091"
    ports:
      - "9091:9091"

  #  wemo-scraper:
  #    depends_on:
  #      - prom-push-gw
  #    build:
  #      context: ./wemo-insight-client
  #      dockerfile: Dockerfile
  #    environment:
  #      WEMO_POLL_TIME: "5"
  #      WEMO_ADDRESS: "192.168.1.25"
  #      WEMO_PORT: "49153"

  tplink-scraper:
    depends_on:
      - prom-push-gw
    build:
      context: ./tplink-hs110-client
      dockerfile: Dockerfile
    environment:
      POLL_TIME_SECONDS: "5"
      TPLINK_HOST: "192.168.1.30"
      PUSH_GW_URL: "http://prom-push-gw:9091/metrics/job/tplink-scraper-1"

volumes:
  grafana-volume:
  prometheus-volume:

