version: '2'
services:

  grafana:
    depends_on:
      - prometheus
    image: alexswilliams/arm32v6-grafana:5.4.3
    volumes:
      - "grafana-volume:/var/lib/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    expose:
      - "3000"
    ports:
      - "3000:3000"

  prometheus:
    depends_on:
      - prom-push-gw
    image: alexswilliams/arm32v6-prometheus:2.6.1
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-volume:/etc/prometheus/data"
    expose:
      - "9090"
    ports:
      - "9090:9090"

  prom-push-gw:
    image: alexswilliams/arm32v6-prometheus-push-gateway:0.7.0
    expose:
      - "9091"
    ports:
      - "9091:9091"

#  wemo-scraper:
#    depends_on:
#      - prom-push-gw
#    build:
#      context: ./wemo-insight-client
#      dockerfile: ./wemo-insight-client/Dockerfile.arm32v6
#    environment:
#      WEMO_POLL_TIME: "1"
#      WEMO_ADDRESS: "192.168.1.25"
#      WEMO_PORT: "49153"

  tplink-scraper:
    depends_on:
      - prom-push-gw
    build:
      context: ./tplink-hs110-client
      dockerfile: ./tplink-hs110-client/Dockerfile.arm32v6
    environment:
      TPLINK_POLL_TIME: "1"
      TPLINK_ADDRESS: "192.168.1.30"

volumes:
  grafana-volume:
  prometheus-volume:

