version: '3.7'
services:
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:5.4.3
    volumes:
      - type: volume
        source: grafana-volume
        target: /var/lib/grafana
        consistency: consistent
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    expose:
      - "3000"
    ports:
      - "3000:3000"
  prometheus:
    depends_on:
      - prom-push-gw
    image: prom/prometheus:2.6.1
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - type: volume
        source: prometheus-volume
        target: /etc/prometheus/data
        consistency: consistent
    expose:
      - "9090"
    ports:
      - "9090:9090"
  prom-push-gw:
    image: prom/pushgateway:0.7.0
    expose:
      - "9091"
    ports:
      - "9091:9091"
  scraper:
    depends_on:
      - prom-push-gw
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WEMO_POLL_TIME: "1"
      WEMO_ADDRESS: "192.168.1.25"
      WEMO_PORT: "49153"

volumes:
  grafana-volume:
  prometheus-volume:

