FROM arm32v6/python:3.8.1-alpine3.11
RUN apk add --no-cache curl

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py entry.sh ./

CMD [ "sh", "./entry.sh" ]
