global:
  scrape_interval:     10s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: prometheus-push-gateway
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - prom-push-gw:9091

  - job_name: prometheus-node-exporter
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 172.19.0.1:9100
