FROM arm32v6/golang:1.12.1-alpine3.9 as build
WORKDIR /go/src/app
COPY src ./
RUN CGO_ENABLED=0 go build -o scraper -ldflags="-s -w" -tags netgo -a ./main

FROM scratch
WORKDIR /app
COPY --from=build /go/src/app/scraper ./

CMD [ "./scraper" ]
